INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("[Trollface].", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A bar-mitzvah.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A black hole.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A chainmail bikini.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A cheap motel.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A dildo.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A glass jar with a preserved two-headed fetal pig.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A grown man crying at a movie.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A hilarious failed suicide attempt.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A husband.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A man pretending to be a woman's "gay friend" in order to get at that sweet vadge.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A molester mustache.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A monolith.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A prosthetic leg.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A self-fulfilling prophecy.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A suspiciously convenient plot device.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A televangelist getting caught picking up male prostitutes.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A toddler-sized coffin.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A wife.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("A wizard's sleeve.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Accidentally sexting your mom.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Anne Frank.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Asians", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Asking her when she's due and finding out she's not pregnant.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Ass-to-mouth.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Assuming all handicapped people are retarded.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Atheists and agnostics.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Attending church.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Bears.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Becoming a Junior High Chess Champion for the sweet hook-ups.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Becoming what you hate.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Bedbugs.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Being "a little pregnant".", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Being friends with somone who is awful, but frequently picks up the check at dinner.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Being happy you just made a gay friend so you can use the phrase "my gay friend"…", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Black Jesus.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Boy bands.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Celebrity beaver shot.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Cellophane underwear.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Childrens' crutches.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Chimpanzees with anger management issues.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Consensual rape.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Crotchless toddler underwear.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Danger! ____ ahead!", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Detroit.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Disney-themed weddings.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Down's Syndrome.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Dressing up in blackface.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Dropkicking anti-Semitic lesbians.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Drunk-texting an ex.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Editing Wikipedia to win an argument.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Encouraging your passenger to moon a bus full of children when you pass it.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Europeans.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Feminists with facial hair.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Finishing off a pint of Ben & Jerry's and knowing you'd have kept eating more if it had been a gallon container.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("First world problems.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Forwarding your grandmother all your erectile dysfunction pill spam.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Frantically clicking pictures of cats on the internet.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Free candy from strangers.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Furries. Yeah, furries.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Gay-marrying your prison rapist.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Getting angry at something just to pass the time.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Getting unfriended by your mom on Facebook.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Giant squid.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Gingers.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Girls Gone Wild.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Hello Kitty.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Human sacrifice.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Indecent exposure.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Jesus.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Lying to terminally ill children about their life expectancy.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Male pregnancy.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Mel Gibson's sanity.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Michigan.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("M-m-m-mocking st-st-st-stutterers.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Mocking autistic children because they don't have feelings.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Mother Theresa's rotting corpse.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Muslims.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Nicholas Cage's storied career.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Not knowing the difference between trolling and being wrong.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("NPR.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Objectsexuals.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Off-duty Nazis just looking for a good time.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Old ladies paying by check.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Performing sex acts learned from Urban Dictionary.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Playing the race card.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Poopcicles.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Public restrooms.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Putting the "fun" in "fundamentalism".", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Putting wheel locks on wheelchairs.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Quoting Monty Python.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Randy gerbils totally macking you.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Realdoll owners.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Reality television.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Reparations for slavery.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Riding the short bus.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Saying "I disapprove of what you say, but I will defend to the death your right to say it" when you know you wouldn't.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Secretly wishing you were born on September 11.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Self-diagnosed Asperger's Syndrome sufferers.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("September 11, 2001.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Sex with vegetables (either kind).", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Sexy nuns.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Sharting.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Sheep.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Slaughtering innocent children.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Smurf-on-smurfette action.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Speaking English instead of American.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Star Wars movies made after 1983.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Starting a cult for tax breaks.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Stepping on a hairball with a bare foot.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Stigmata.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Stunt cock.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Surprise buttsecks.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Swingers.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Synchronized Sneezing.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("That "not-so-fresh" feeling.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("That feeling when you encounter a handicapped person waiting for you to leave the largest stall in a restroom.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The 911 Truther movement.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The ancient martial art of Flung Poo.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The Challenger explosion.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The Civil War.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The lonliest Brony.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("The Tea Party.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Toast with the burned image of Our Lord and Savior, Jesus Christ.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Tossing a salad.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Vagina dentata.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Vorpal Dildo of Enlightenment +2.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("War crimes.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Watching a Twilight movie on purpose.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Wearing extra thin pants for a strip club lap dance.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Wolf-whistling at Girl Scouts.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Women.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Wondering if it was something you did which caused your significant other to become gay.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Wondering if the colorblind have an equally useless superpower.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Your aunt barging into the bathroom when you're pooping.", "ricin", "R");
INSERT INTO `white_cards`(`text`, `creator`, `watermark`) VALUES ("Your grandpa sucking some dicks to not get drafted.", "ricin", "R");
